### ISSUE TITLE
current slipcast-cli release broken

### ISSUE THREAD

**Issue by jonknapp** [CoffeeAndCode/slipcast#48]
Trying to create a project returns an error similar to the following:

```
module.js:472
    throw err;
    ^

Error: Cannot find module './platform'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jon/.config/yarn/global/node_modules/slipcast-cli/lib/createApp.js:6:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by jonknapp** [comment]
Fixed!
